apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: enterprise-system-20260626-004613-083jm7srng0p-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: enterprise-system-20260626-004613-083jm7srng0p.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: enterprise-system-20260626-004613-083jm7srng0p-service
            port:
              number: 80
