apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260626-004613-083jm7srng0p-service
spec:
  selector:
    app: enterprise-system-20260626-004613-083jm7srng0p
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
